-- Profile / Contact Info Table
create table if not exists profile (
  id bigint generated by default as identity primary key,
  email text,
  social_upwork text,
  social_linkedin text,
  social_tiktok text,
  social_onlinejobs text,
  social_github text,
  contact_subtext text,
  rush_available boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Policies
create policy "Public profile is viewable by everyone." on profile for select using (true);
create policy "Public users can manage profile." on profile for all using (true);
alter table profile enable row level security;

-- Default Data (Upsert default if not exists)
insert into profile (id, email, social_upwork, social_linkedin, social_tiktok, social_onlinejobs, social_github, contact_subtext, rush_available)
values (
  1, 
  'benzsiangco@gmail.com', 
  'https://www.upwork.com/freelancers/~01a117d57b162100540?s=1044578476142100540', 
  'https://www.linkedin.com/in/jessie-benz-siangco-578671263/', 
  'https://www.tiktok.com/@benz.gfx', 
  'https://www.onlinejobs.ph/jobseekers/info/2910849', 
  'https://github.com/Malphite31', 
  'Ready to elevate your content? Reach out for collaboration. I respond within 24 hours.', 
  true
)
on conflict (id) do nothing;
