-- Skills Table
create table if not exists skills (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null, -- 'Editor', 'Language', 'Software', 'Other'
  icon_url text, -- Optional icon
  proficiency int default 0, -- 0-100
  sort_order float default 0,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Analytics: Site Visits
create table if not exists site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text, -- Anonymous ID stored in local storage
  user_agent text,
  page text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Analytics: Project Views
create table if not exists project_views (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Policies (Public Read, Admin Write/All - using the "public writes allowed" model for this personal project as established)
create policy "Public skills are viewable by everyone." on skills for select using (true);
create policy "Public users can manage skills." on skills for all using (true);

create policy "Public can insert visits." on site_visits for insert with check (true);
create policy "Admins can view visits." on site_visits for select using (true);

create policy "Public can insert project views." on project_views for insert with check (true);
create policy "Admins can view project views." on project_views for select using (true);

-- Enable RLS
alter table skills enable row level security;
alter table site_visits enable row level security;
alter table project_views enable row level security;
